version: '3'

services:
    php-fpm:
      build: docker/php
      working_dir: /var/www/Log
      volumes:
          - ./:/var/www/Log

    elasticsearch:
      image: docker.elastic.co/elasticsearch/elasticsearch:6.2.2
      container_name: log-elasticsearch
      environment:
        - cluster.name=docker-cluster
        - bootstrap.memory_lock=true
        - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      ulimits:
        memlock:
          soft: -1
          hard: -1
      ports:
        - 9200:9200